### ISSUE TITLE
Pattern Loading: dataset name not restored, round termination incorrectly loaded 

### ISSUE THREAD

**Issue by NicoWeidmann** [bendixsonnenberg/CS-Select#103]
When loading a previously saved pattern, the dataset name is not loaded from the pattern. When storing a round termination in the pattern, it looks like this when loading:
![bildschirmfoto 2019-02-07 um 13 57 52](https://user-images.githubusercontent.com/24777609/52412896-6100e400-2ae0-11e9-89c0-225e7381d0be.png)

Nothing happens when clicking on "Create" (not even an error message).

**Comment by bendixsonnenberg** [comment]
@SeineEloquenz the database needs to store the featureSet for each pattern

**Comment by Jakob-Bach** [comment]
Related (maybe cause?): `GameOptions::clone()` does not set dataset.
