### ISSUE TITLE
Game Creation: setting "<script>alert("XSS from game title")</script>" as title leads to null in DB 

### ISSUE THREAD

**Issue by NicoWeidmann** [bendixsonnenberg/CS-Select#104]
Setting `<script>alert("XSS from game title")</script>` as title of a new game leads to a `NULL` entry in the database for the new game's name. After restarting the server, the game is shown without a title in the organizer dashboard.

At least you are not vulnerable to very simple XSS in the game title 👍

**Comment by NicoWeidmann** [comment]
the following titles are correctly stored in the DB:
- `<b`
- `/`
- `""`

**Comment by SeineEloquenz** [comment]
The title was simply too long for the column, I increased the maximum character count.

**Comment by NicoWeidmann** [comment]
Oops, I could have thought of that. You might want to consider to add a check for input length.
