### ISSUE TITLE
[code][low prio] `Termination` naming could be made static

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#109]
I wonder why `Termination::getName()` is an instance method and not a static method - it looks strange in `TerminationParser` that dummy objects have to be created to compare the type of termination. *type* could also be a better name for this property than *name*.

**Comment by Jakob-Bach** [comment]
The same applies to `Gamemode`.

**Comment by SeineEloquenz** [comment]
As no more dummy objects need to be created in the parsers since the rewrite by @bendixsonnenberg I'm closing this
