### ISSUE TITLE
[cocde][low prio] `Leaderboard` not thread-safe

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#112]
The current singleton implementation of `Leaderboard` is not thread-safe. I suppose it's not a big problem in our standard use case, as we won't have that much parallelization, but still, there are some alternatives:
- https://dzone.com/articles/all-about-the-singleton
- https://www.journaldev.com/171/thread-safety-in-java-singleton-classes-with-example-code (e.g. enum solution looks fine in our case)

**Comment by Jakob-Bach** [comment]
The same applies to the `Injector`.

**Comment by SeineEloquenz** [comment]
Injector made thread-safe as of 6f53e262d0426a0cb2a62aacfe271f7357cd41bd
