### ISSUE TITLE
[code][low prio] Remove `UserManagement::register()`

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#114]
From a design perspective, it is not a good idea to create a super-class method if it's parameterized differently in sub-classes - using a string array to account for variable length of the parameter list reduces readability greatly. Furthermore, even in the current implementation, there is no benefit of `UserManagement::register()`, as the method is only called in `APIFacadePlayer::register()` and `APIFacadeOrganiser()` directly on sub-class objects of type `PlayerManagement`/`OrganiserManagement`, so there is no dynamic dispatch where a super-class method could be useful.

**Comment by Jakob-Bach** [comment]
Same applied to `Login`.

**Comment by Weitspringer** [comment]
Solved by f38a76ae27d2b2ddd8c87f8bc6618a2cf64d748a
