### ISSUE TITLE
[code][low prio] Move salting to encryption

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#115]
The `Encrypter.encrypt()` takes one string as parameter. Currently, this is always a salted password, having the concatenation of password and salt as manual, preliminary step at various locations before calling `encrypt()`, which is potentially error-prone (e.g. if someone forgets salting or changes the order in the concatenation). Thus, it would make sense to move salting directly into the `encrypt()` method.

**Comment by SeineEloquenz** [comment]
Fixed as of 15277a94f40a4b579352689a440a2059f42bedd3
