### ISSUE TITLE
[code] `Termination` and `Gamemode` hard-coded in `MysqlAdapter` 

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#118]
`MysqlAdapter::parseGamemode()` and `MysqlAdapter::parseTermination()` contain some hard-coded strings, referring to the `toString()` methods of `Gamemode` and `Termination`. This is dangerous in case of changes. The strings could be made constants in the `Gamemode` and `Termination` class or even the whole parsing could be moved to static methods in `Gamemode` and `Termination` (as it is the reverse operation to `toString()` and should therefore be placed at the same location). Maybe the parsing here and the classes in `parser` can be combined.

**Comment by SeineEloquenz** [comment]
Moved to constants as of 8b7df73
