### ISSUE TITLE
[code][low prio] Make English default language in database

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#120]
`MysqlOrganiserAdapter` and `MysqlPlayerAdapter` create new users with German as default language. To be consistent with the mails, English should be the default.

**Comment by Jakob-Bach** [comment]
I would also change it in `Servlet`.

**Comment by SeineEloquenz** [comment]
In database fixed as of d10063a07be86f21f14cb807aa2e4625fe5f187f

**Comment by bendixsonnenberg** [comment]
no need to change anything in the frontend, language is never set during registration
