### ISSUE TITLE
[code] Add stronger assertions to parser tests

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#124]
If there were getter methods in the `Termination` and `Gamemode` sub-classes, you could run proper tests of the parsers, not just a not-null check which cannot fail. Considering that string parsing is a potentially error-prone operation, it would make sense to introduce such tests.

- [x] `GamemodeParserTest`
- [x] `TerminationParserTest`

**Comment by Weitspringer** [comment]
If we cast these object to a specific class, there is the possibility of get null objects (in case the cast is not valid)
