### ISSUE TITLE
When creating the first game, it only works on the second attempt

### ISSUE THREAD

**Issue by bendixsonnenberg** [bendixsonnenberg/CS-Select#132]
the first time the server returns 202, meaning that ``Organiser::create()`` has been called, but no new game has been created.
this is quite obvious, as the game created message returns way too quick for a new database to be created

**Comment by SeineEloquenz** [comment]
How can we solve this? Shouldn't the message wait for a response from the backend?

**Comment by bendixsonnenberg** [comment]
some kind of response on ``Organiser::create```whether the game has been created. currently it returns void

**Comment by bendixsonnenberg** [comment]
also the first game isn't created, which is also wrong, since all the neccissary values have been supplied

**Comment by SeineEloquenz** [comment]
It is not saved to the database? Could you debug this as I don't have my mysql workspace ready until monday

**Comment by SeineEloquenz** [comment]
For the `Organiser::create` I would propose a boolean return  through a null check on the game as the gamecreator returns null when the game can't be created

**Comment by bendixsonnenberg** [comment]
not saved to the database, no new database created.

**Comment by SeineEloquenz** [comment]
This then will have to wait until monday when I can properly investigate again

**Comment by SeineEloquenz** [comment]
#134

**Comment by bendixsonnenberg** [comment]
currently i cant reproduce this on the current master
