### ISSUE TITLE
Games are on the bottom of the page if leaderboard contains many players

### ISSUE THREAD

**Issue by Santaaa348** [bendixsonnenberg/CS-Select#136]
![leaderboard](https://user-images.githubusercontent.com/37215789/52526465-4e8dd280-2cb9-11e9-80da-21c85a473e21.PNG)

**Comment by bendixsonnenberg** [comment]
this is to be expected, the solution would be to not show as many players in the leaderboard

**Comment by SeineEloquenz** [comment]
I would propose to only show the top 10 players

**Comment by bendixsonnenberg** [comment]
even 10 players will throw of the layout of the page as you can see in the image
i'd go for the top 5

**Comment by Santaaa348** [comment]
How about making it scrollable?

**Comment by bendixsonnenberg** [comment]
in any case i would not display all players as it would somehow 'shame' players that don't achieve many points.
making it scroll-able would make it rather annoying to use on mobile

**Comment by SeineEloquenz** [comment]
I agree that top 5 seems to be the best solution

**Comment by bendixsonnenberg** [comment]
do we do this in the backend or the frontend?
I'd say backend, because that would reduce the amount of data sent

**Comment by SeineEloquenz** [comment]
I agree, Leaderboard should only give out a top 5 list

**Comment by Santaaa348** [comment]
Done in 5363b603369a1e6c03e9f28902c6fac2c69a4692 (might still look into performance later)..
