### ISSUE TITLE
skipped rounds count towards rounds termination

### ISSUE THREAD

**Issue by bendixsonnenberg** [bendixsonnenberg/CS-Select#137]
this should not happen,but yet does

**Comment by SeineEloquenz** [comment]
Skipped rounds get added to finished rounds like every other round and are therefore not distinguished further down in the system, @Biekachuu might take a look into this

**Comment by Biekachuu** [comment]
There are 2 different ways to solve this, either make an extra table for skipped rounds or make skipped rounds not count for the number of rounds of a game. @SeineEloquenz What do you prefer?

**Comment by SeineEloquenz** [comment]
I prefer the latter and intend to add a `skipped` boolean attribute to rounds, with which I can filter out skipped rounds directly when loading them

**Comment by Biekachuu** [comment]
Rounds now have the boolean attribute and a getter for it
