### ISSUE TITLE
Fix logo scaling on login screen (Chrome)

### ISSUE THREAD

**Issue by NicoWeidmann** [bendixsonnenberg/CS-Select#138]
<img width="1440" alt="bildschirmfoto 2019-02-09 um 23 22 42" src="https://user-images.githubusercontent.com/24777609/52526993-af210d80-2cc1-11e9-9364-437e5964b125.png">

**Comment by SeineEloquenz** [comment]
Did you try hard-reloading the webpage? We had this before and the page was still cached

**Comment by NicoWeidmann** [comment]
thanks, that did the trick.
