### ISSUE TITLE
[gui][low prio] Further improve mail invitation field

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#152]
Follow-up to #84:
- [ ] Similar to the existing improvement of invitations in the game creation process, the invitation functionality for running games can be adapted.
- [x] Modi "Single" and "Mass" not translated to German
- [x] Modi "Single" and "Mass" have no description. It's not really clear that they refer to the invitation field unless you click on them. Instead of a description, you could maybe simply place them below the input field.

**Comment by bendixsonnenberg** [comment]
#142
