### ISSUE TITLE
When not selecting the right amount of features in binaryselect(5 out of 10) the round is not saved an a score of -1 is returned

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#153]
- [x] A player can toggle features useless and still select them. I did this for all 5 sub-rounds in binary select and got a final round score of -1; the round was not saved in the database.
- [x] You could think about the streak mechanism if only useless (according to the view of the player) features are presented. If playing honestly, the player marks all features as useless and then skips the round. However, this destroys the streak.
- [x] You could also think of sub-round skipping. Currently, only whole rounds can be skipped. However, it might be that e.g. only 1 of 5 selections in binary mode cannot be answered by the player, but the rest could.

**Comment by bendixsonnenberg** [comment]
would it work, that if both features are marked useless, the next two features are shown in binarySelect?

**Comment by Jakob-Bach** [comment]
As product owner, I would be satisfied with a solution showing a new pair of features if both are marked useless (maybe with some notification/help so that the user is not confused once this happens).

**Comment by bendixsonnenberg** [comment]
is there anything left to do on this issue?

**Comment by Biekachuu** [comment]
Don't think so
