### ISSUE TITLE
[gui][low prio] Further improve Achievement View

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#159]
Follow-up to #97: Concealed achievements look a bit strange with their empty frame (might be considered a bug by the user). Furthermore, I don't know if not displaying invisible achievements at all is the best solution, as players might be more motivated if they already knew the total number of achievements (as long as not there still are invisible ones; one might argue the opposite direction once all are at least concealed). Thus, one could also display invisible achievements with no text at all and concealed achievements with only the title shown.

![screenshot](https://user-images.githubusercontent.com/6431179/52560501-dcbca280-2df8-11e9-9fc0-771cc3fd7cdd.PNG)

**Comment by Santaaa348** [comment]
There are no empty frames anymore, achievements with the state `INVISIBLE` now have a title `Unknown` with a tooltip that explains this state.
