### ISSUE TITLE
[bug][gui] Encoding problem in German version

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#160]
Non-standard characters like German "Umlaute" not properly displayed.
Setup: Firefox, `mvn package` build.

![capture](https://user-images.githubusercontent.com/6431179/52561048-8486a000-2dfa-11e9-940a-e25051b88fc8.PNG)

**Comment by bendixsonnenberg** [comment]
which os are you using?

**Comment by Jakob-Bach** [comment]
Windows

**Comment by bendixsonnenberg** [comment]
I can't debug this, as it does not happen on linux, someone else will have to look into it  
I'd say it has something to do with the page encoding, but I can't be sure

**Comment by SeineEloquenz** [comment]
I know that this happens on my machine as well, if you can tell me what I should look for on the webpage I could take a look into it

**Comment by SeineEloquenz** [comment]
I'll check

**Comment by SeineEloquenz** [comment]
That did the trick, working for me

**Comment by bendixsonnenberg** [comment]
I hate HTML

**Comment by Weitspringer** [comment]
Works for me too

**Comment by SeineEloquenz** [comment]
Then I will close this as it seems to be fixed
