### ISSUE TITLE
SQLSyntaxErrorException when creating game

### ISSUE THREAD

**Issue by Weitspringer** [bendixsonnenberg/CS-Select#163]
Create Game with new organiser, do following, then hit create:

![screenshot 12](https://user-images.githubusercontent.com/35311367/52576296-1c4ab500-2e20-11e9-8da9-ef6a69480d53.png)

So it is the first game created by a new Organiser.
Shows following in terminal:
`ERROR: java.sql.SQLSyntaxErrorException: Unknown column 'dataset' in 'field list'
tomcat_1    |   at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
tomcat_1    |   at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
tomcat_1    |   at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)`

**Comment by Weitspringer** [comment]
`tomcat_1    |   at com.csselect.database.mysql.MysqlOrganiserAdapter.addPattern(MysqlOrganiserAdapter.java:81)
tomcat_1    |   at com.csselect.user.Organiser.savePattern(Organiser.java:45)
tomcat_1    |   at com.csselect.API.APIFacadeOrganiser.savePattern(APIFacadeOrganiser.java:125)
tomcat_1    |   at com.csselect.API.httpAPI.GameManagement.savePattern(GameManagement.java:156)`

**Comment by Weitspringer** [comment]
Game is created, though. But Create-Button becomes permanently disabled when not reloading the page

**Comment by bendixsonnenberg** [comment]
have you tried droping the database schema?
the dataset column was add recently and might not exists in your pattern table

**Comment by Weitspringer** [comment]
That is the odd thing: I have a database column

**Comment by SeineEloquenz** [comment]
Could you please post a screenshot of your pattern table because I can't reproduce this on the current master

**Comment by Weitspringer** [comment]
`ERROR: java.sql.SQLSyntaxErrorException: Unknown column 'skipped' in 'where clause'
tomcat_1    |   at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
tomcat_1    |   at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
tomcat_1    |   at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
tomcat_1    |   at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:974)
tomcat_1    |   at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1024)
tomcat_1    |   at com.csselect.database.mysql.MysqlDatabaseAdapter.executeMysqlQuery(MysqlDatabaseAdapter.java:359)
tomcat_1    |   at com.csselect.database.mysql.MysqlGameAdapter.getNumberOfRounds(MysqlGameAdapter.java:102)
tomcat_1    |   at com.csselect.game.Game.getNumberOfRounds(Game.java:70)
tomcat_1    |   at com.csselect.game.NumberOfRoundsTermination.checkTermination(NumberOfRoundsTermination.java:25)
tomcat_1    |   at com.csselect.game.Game.isTerminated(Game.java:89)
tomcat_1    |   at com.csselect.game.Game.invitePlayers(Game.java:224)
tomcat_1    |   at com.csselect.game.gamecreation.GameCreator.doCreate(GameCreator.java:117)
tomcat_1    |   at com.csselect.user.Organiser.createGame(Organiser.java:72)`

**Comment by Weitspringer** [comment]
Column is found, but now there is this error

**Comment by Weitspringer** [comment]
(I invited luca@yahoo.com before creating)

**Comment by SeineEloquenz** [comment]
Please post screenshots of the tables from workbench

**Comment by SeineEloquenz** [comment]
Please screenshot the tables so I can see what is going on.
Did you drop schemata before redeploying the current master?

**Comment by Weitspringer** [comment]
Yes

**Comment by Weitspringer** [comment]
![screenshot 18](https://user-images.githubusercontent.com/35311367/52577785-1b675280-2e23-11e9-8af9-a6a17e3b4507.png)

![screenshot 16](https://user-images.githubusercontent.com/35311367/52577791-202c0680-2e23-11e9-939f-1072329d198b.png)

**Comment by SeineEloquenz** [comment]
Please screenshot the `CS_SELECT.patterns` table

**Comment by Weitspringer** [comment]
By the way, luca@yahoo.com was not invited, this email was invited after this creation now (I dropped first CS-Select, then created test, then dropped test, then created same game again)

**Comment by Weitspringer** [comment]
![screenshot 19](https://user-images.githubusercontent.com/35311367/52577891-65e8cf00-2e23-11e9-8143-0f3507fc9dab.png)
Normal!!!

**Comment by Weitspringer** [comment]
So pattern creating IS working, but we have another problem

**Comment by Weitspringer** [comment]
So when inviting players to a game in creation, the game checks if it is terminated. Could be that there occurs an error

**Comment by bendixsonnenberg** [comment]
did you try to drop the game database (i.e. test). The skipped column was also added recently

**Comment by Weitspringer** [comment]
Yes I did.Looking into it on Wednesday, for now i am off the machine. Until then this shall be low prio
 
 
  Am Mo., Feb. 11, 2019 at 17:42 schrieb Bendix Sonnenberg<notifications@github.com>:   
did you try to drop the game database (i.e. test). The skipped column was also added recently

**Comment by bendixsonnenberg** [comment]
On current master i can create games without error

**Comment by SeineEloquenz** [comment]
On mine as well so I believe the problem lies on @Weitspringer's end

**Comment by Weitspringer** [comment]
Testing this now

**Comment by Weitspringer** [comment]
Solution: Had to add email properties from example config file of this project to the config file of tomcat docker container (config/Catalina/cs_select) .
