### ISSUE TITLE
Clicking on next with no features selected

### ISSUE THREAD

**Issue by Santaaa348** [bendixsonnenberg/CS-Select#164]
`Matrix Select` When you select the minimum amount of features and then toggle all of them useless (without unselecting), you are still able to (accidentally) click `Next` and the game breaks (you have to go back to the player dashboard).
With the same trick you could also click on `Next` with less features selected than wanted by the organiser.

**Comment by Santaaa348** [comment]
Similar thing in `BinarySelect`. When you accidentally click on `next` after toggling all features as useless, the same thing happens (as the ML-Server expects at least one feature).

**Comment by Biekachuu** [comment]
This treats the round as a normal round with 0 points, but we could also treat it like a skipped round as no features are selected, what do you prefer?

**Comment by Santaaa348** [comment]
Maybe you can block the toggle-button when a feature is selected. @bendixsonnenberg I believe this could fix the `Matrix Select` problem (?)

I don't think this should be treated as a round. @Biekachuu

**Comment by bendixsonnenberg** [comment]
> This treats the round as a normal round with 0 points, but we could also treat it like a skipped round as no features are selected, what do you prefer?

I'd say we count it as a skipped round with all features marked useless

**Comment by Biekachuu** [comment]
Changed it but no rounds with 0 selected features should get to the backend as non skipped rounds anymore anyways, right?

**Comment by bendixsonnenberg** [comment]
correct

**Comment by Santaaa348** [comment]
Is this fixed @Biekachuu? At least it seems to work.

**Comment by Biekachuu** [comment]
Should be fixed yeah
