### ISSUE TITLE
[feature-request] Handle database existence on game creation

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#166]
When creating a game from a pattern, the database field is also pre-filled. Several times I overlooked this and thus created a new game using an existing database. This should be prevented.

**Comment by bendixsonnenberg** [comment]
What would be the solution to this?
- [ ] not saving the database in the pattern, or
- [ ] checking whether the database exists and then refusing to create the game, or
- [ ] checking whether the database exist, asking the user whether they are sure about overwriting the database
@SeineEloquenz in case of the latter 2 we will need some kind of databaseExists() call on the DatabaseAdapter

**Comment by SeineEloquenz** [comment]
I would opt for number 1, as we already check for duplicate databases once they are created if I'm correct. We could as well improve the already existing checkDuplicateDatabase method by also checking if the database ist listed in the databasename column if it is not already created

**Comment by Jakob-Bach** [comment]
Regardless if saving the database name in the pattern or not, I would recommend doing the existence check and notifying the user accordingly (ideally, with an overwrite dialogue).

**Comment by Weitspringer** [comment]
@SeineEloquenz Does a method exist which checks if a result database with a specific title exists already?

**Comment by SeineEloquenz** [comment]
Yes. checkDuplicateDatabase in DatabaseAdapter. I don't know if it's available in the api for an axios call
