### ISSUE TITLE
[bug][low prio] Creating two patterns with same name possible

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#167]

**Comment by Weitspringer** [comment]
Should we completely deny overwriting the pattern or put in a warning asking the organiser if he intended that?

**Comment by Jakob-Bach** [comment]
A warning would be fine.

**Comment by Weitspringer** [comment]
I am looking into that

**Comment by Jakob-Bach** [comment]
The issue also occurs for game titles, so if a solution is found for the patterns, it can simply be adapted to titles as well.

**Comment by Weitspringer** [comment]
@SeineEloquenz 
Could you implement in the database backend adding a pattern with existing title overwrites the pattern in the database?

**Comment by Weitspringer** [comment]
On branch pattternOverwriteWarning

**Comment by Weitspringer** [comment]
If this works we will look for the games

**Comment by SeineEloquenz** [comment]
@Jakob-Bach shouldn't multiple games with the same title be allowed? As we distinguish between games solely by their ids, we would prevent different organisers who might have completely different players from picking the same titles. Do we really want this behaviour?

**Comment by SeineEloquenz** [comment]
@Weitspringer working on it

**Comment by Jakob-Bach** [comment]
@SeineEloquenz My idea was that players could be confused when seeing two games with the same title. By using patterns, creating games with the same title might occur by accident (organisers overlook changing some fields). Thus, I would at least issue a warning if organisers wants to create a game with a title they have already used *themselves*. The case of different organisers picking same name and inviting same player does not need to be addressed (not likely apart from testing scenarios).

**Comment by Weitspringer** [comment]
#183

**Comment by Weitspringer** [comment]
To check if the game exists, we would need to load all active games which were created by the organiser. Could be that - if there are many of them - the page needs really long to load.

**Comment by SeineEloquenz** [comment]
Thanks for clarifying @Jakob-Bach
@Weitspringer we might as well add a method in the databaseadapter which takes an organiser and a title and checks if the title is already used

**Comment by Weitspringer** [comment]
If we want changes to the Backend we could do that. Seems faster.

**Comment by SeineEloquenz** [comment]
Gonna work on it

**Comment by SeineEloquenz** [comment]
@Weitspringer method is ready

**Comment by Weitspringer** [comment]
Relates to #166
