### ISSUE TITLE
[low prio] Improve invitation mail

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#168]
- [x] Add URL to application
- [x] Maybe add some details about game, like name.

**Comment by bendixsonnenberg** [comment]
@SeineEloquenz to add the url to the application, we will need a way to get the address to the tomcat server, so i'd say we get that from the properties file

**Comment by SeineEloquenz** [comment]
You mean adding the application url to the config?

**Comment by bendixsonnenberg** [comment]
yes

**Comment by SeineEloquenz** [comment]
5a5cc8f added the config setting @bendixsonnenberg. Docker repo still has to be updated

**Comment by SeineEloquenz** [comment]
Added the value to the docker repo, all users of the docker-compose solution will have to update

**Comment by SeineEloquenz** [comment]
Game name as well as application url are now added to the invitation mails as of 144aff7694d4d295b18b2ffc0320a4924a2ba4b6
