### ISSUE TITLE
[bug][gui] Encoding problem for features

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#175]
Features names/titles not properly encoded (Windows, Firefox).

![screenshot](https://user-images.githubusercontent.com/6431179/52646419-0225db00-2ee3-11e9-9274-d780bec99093.PNG)

`summary.json` returned by ML server should be UTF-8-encoded.

**Comment by bendixsonnenberg** [comment]
[stackoverflow](https://stackoverflow.com/questions/13350676/how-to-read-write-this-in-utf-8)

**Comment by SeineEloquenz** [comment]
Should be fixed by a6ec231e9277bf048bc2bf913f0c22d27a91c7f7, at least on my end

**Comment by Jakob-Bach** [comment]
Looks good for me from end-user perspective.

**Comment by SeineEloquenz** [comment]
Then I'm gonna close this issue as it seems to be fixed
