### ISSUE TITLE
[bug][gui] Game termination message if players quit game

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#176]
If players choose to stop playing a game by themselves (use the *quite* button), they still get the `The game you were playing has terminated. You have been returned to the dashboard` message.

**Comment by bendixsonnenberg** [comment]
should have been fixed in 3dc61f4a121033f595a63a5c3c1f9c3cd36e8533
did do a hard reload of the page?

**Comment by Jakob-Bach** [comment]
Ok, was a caching issue.
