### ISSUE TITLE
[gui][feature-request] Show invited mails during game creation

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#179]
Mail addresses entered during game creation disappear after pressing the corresponding button. Organisers with bad short-term memory might forget which addresses they have already entered. Plus (and more serious), invited mails are also part of patterns, so when loading a pattern, you have no clue which players are pre-selected for invitation (unless you look into the database). Thus, it would be nice to have an additional read-only component showing the list of players already selected for invitation. Even better would be a list where individual elements can also be deleted.

**Comment by bendixsonnenberg** [comment]
a list of all pinvited players can be shown in the mass invitation field. In that field are also the players from patterns shown

**Comment by Jakob-Bach** [comment]
- [ ] Currently I can't see invited players in mass invitation field if loading a pattern.
- [ ] Using the mass invitation field to review selected players is a solution, but not really intuitive, giving the the current label *Invite multiple players*.
