### ISSUE TITLE
[gui][feature-request] Improve game info on dashboards

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#180]
- [x] For players: termination
- [ ] For organisers: basically all game creation info from the database
- [ ] For organisers: game progress info; at least rounds played, but num skipped, average quality, average points, num useless would also be nice (in theory, you could include many statistics, also on individual players, but that's out of scope - it's only important that the organiser has some basic understanding of the game progress, e.g. for manual termination)

**Comment by bendixsonnenberg** [comment]
I'll need getters on the game for any metric we want to display in the frontend

**Comment by bendixsonnenberg** [comment]
We will not show the additional information for organsiers
