### ISSUE TITLE
[code] Player and User implementing Comparable

### ISSUE THREAD

**Issue by NicoWeidmann** [bendixsonnenberg/CS-Select#185]
Currently, Player and Organiser implement the interface `Comparable`. Objects of each of these classes can only be compared to other objects of the same class. Currently, calls to `compareTo` fail with an exception if called with an object that doesn't meet this condition.

This should be avoided by implementing `Comparable<Player>` or `Comparable<Organiser>` instead of the raw type `Comparable`.

Additionally, the [specification](https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html) says that the compareTo method defines a "natural ordering" for a class. I don't see how ordering by IDs is the natural ordering for Players or Organisers. In fact, I don't see a natural ordering for those two classes.

If you want to keep ordering by ID in the compareTo method, you can also think about moving the functionality to the parent class User, as the implementation for Player and Organiser is nearly the same.

**Comment by Weitspringer** [comment]
Its the ordering by timeline. Users with smaller int as ID are longer in our system than Users with greater ID. So I would say thats the intuitive ordering.
We differ between Player IDs and Organiser IDs
