### ISSUE TITLE
Game Creation: player can be invited multiple times

### ISSUE THREAD

**Issue by NicoWeidmann** [bendixsonnenberg/CS-Select#186]
The frontend allows for adding one e-mail address to the invited list multiple times:
<img width="380" alt="bildschirmfoto 2019-02-13 um 16 58 57" src="https://user-images.githubusercontent.com/24777609/52725066-c5c0b080-2fb0-11e9-8e9f-5d17a9cc9cb7.png">

**Comment by Weitspringer** [comment]
Looking into it
