### ISSUE TITLE
[bug][gui] OrganiserTermination still not shown in CompositeTermination

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#188]
... which make the "Add" field quite useless at the moment. Follow-up to #182.

**Comment by SeineEloquenz** [comment]
@bendixsonnenberg I would opt to simply remove the add field, as adding organiser termination to a composite doesn't make sense. Maybe we can comment it out in the jsp with an according comment and documentation entry to have it easily available if new termination methods came into place that actually make sense in a composite
