### ISSUE TITLE
startRound for valid game returns null

### ISSUE THREAD

**Issue by bendixsonnenberg** [bendixsonnenberg/CS-Select#19]
calling startRound with a valid gameId returns null

**Comment by bendixsonnenberg** [comment]
Steps to reproduce: 
 - create organiser account
 - create player account
 - create game with organiser account and invite player account
 - accept invite with player account
 - start game with player account
 - startround will return null

**Comment by SeineEloquenz** [comment]
Can't reproduce the bug, when should the nullpointer be thrown? When clicking on "Play" on the player overview?

**Comment by SeineEloquenz** [comment]
With the last commit terminations don't get their games assigned anymore, are you sure this is correct behavior @Biekachuu?

**Comment by Biekachuu** [comment]
Found likely cause of the bug (game object created by database may not have
had a FeatureSet so there were no features to return) and fixed it

Am Do., 31. Jan. 2019 um 20:54 Uhr schrieb Nicholas Bieker <
bieker.nicholas@gmail.com>:

**Comment by SeineEloquenz** [comment]
Fixed another mistake, please check if error still occurs @bendixsonnenberg

**Comment by bendixsonnenberg** [comment]
@SeineEloquenz  i cant reproduce the javascript errors, and i am still getting a null pointer exception when calling startRound
```
java.lang.NullPointerException
	com.csselect.game.Round.setGame(Round.java:49)
	com.csselect.game.Game.startRound(Game.java:283)
	com.csselect.user.Player.lambda$startRound$2(Player.java:79)
	java.base/java.lang.Iterable.forEach(Iterable.java:75)
	com.csselect.user.Player.startRound(Player.java:77)
	com.csselect.API.APIFacadePlayer.startRound(APIFacadePlayer.java:129)
	com.csselect.API.httpAPI.Games.startRound(Games.java:108)
	com.csselect.API.httpAPI.Games.post(Games.java:64)
	com.csselect.API.httpAPI.Servlet.doPost(Servlet.java:97)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53
```

**Comment by bendixsonnenberg** [comment]
found in the logs for the tomcat server:
```
java.io.FileNotFoundException: /test/CSSelect/dataSetName/summary.json (No such file or directory)
tomcat_1    | 	at java.base/java.io.FileInputStream.open0(Native Method)
tomcat_1    | 	at java.base/java.io.FileInputStream.open(FileInputStream.java:220)
tomcat_1    | 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
tomcat_1    | 	at java.base/java.io.FileReader.<init>(FileReader.java:72)
tomcat_1    | 	at com.csselect.utils.FeatureSetUtils.loadFeatureSet(FeatureSetUtils.java:38)
tomcat_1    | 	at com.csselect.database.mysql.MysqlGameAdapter.getFeatures(MysqlGameAdapter.java:80)
tomcat_1    | 	at com.csselect.game.Game.getFeatureSet(Game.java:134)
tomcat_1    | 	at com.csselect.game.Round.setGame(Round.java:49)
tomcat_1    | 	at com.csselect.game.Game.startRound(Game.java:283)
tomcat_1    | 	at com.csselect.user.Player.lambda$startRound$2(Player.java:79)
tomcat_1    | 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
tomcat_1    | 	at com.csselect.user.Player.startRound(Player.java:77)
tomcat_1    | 	at com.csselect.API.APIFacadePlayer.startRound(APIFacadePlayer.java:129)
tomcat_1    | 	at com.csselect.API.httpAPI.Games.startRound(Games.java:108)
tomcat_1    | 	at com.csselect.API.httpAPI.Games.post(Games.java:64)
tomcat_1    | 	at com.csselect.API.httpAPI.Servlet.doPost(Servlet.java:97)
tomcat_1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
tomcat_1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
```

**Comment by bendixsonnenberg** [comment]
Can the reason be that the files from the ml server are not properly saved? Or that our process hasn't got the right priviliges to edit files

**Comment by SeineEloquenz** [comment]
The home directory path in the config that lays in `conf/Catalina/cs_select`is not correct. You need to change it to one where the tomcat process has write permission

**Comment by bendixsonnenberg** [comment]
is the homedir folder created if it does not exist?

**Comment by bendixsonnenberg** [comment]
i also get the following in the tomcat log:

```
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'database' at line 1
tomcat_1    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
tomcat_1    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
tomcat_1    | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
tomcat_1    | 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
tomcat_1    | 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
tomcat_1    | 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
tomcat_1    | 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207)
tomcat_1    | 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:402)
tomcat_1    | 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:125)
tomcat_1    | 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:110)
tomcat_1    | 	at com.csselect.database.mysql.MysqlDatabaseAdapter.executeMysqlUpdate(MysqlDatabaseAdapter.java:370)
tomcat_1    | 	at com.csselect.database.mysql.MysqlGameAdapter.addInvitedPlayers(MysqlGameAdapter.java:246)
tomcat_1    | 	at com.csselect.game.Game.invitePlayers(Game.java:219)
tomcat_1    | 	at com.csselect.game.gamecreation.GameCreator.doCreate(GameCreator.java:109)
tomcat_1    | 	at com.csselect.user.Organiser.createGame(Organiser.java:73)
tomcat_1    | 	at com.csselect.API.APIFacadeOrganiser.createGame(APIFacadeOrganiser.java:138)
tomcat_1    | 	at com.csselect.API.httpAPI.GameManagement.createGame(GameManagement.java:150)
tomcat_1    | 	at com.csselect.API.httpAPI.GameManagement.post(GameManagement.java:58)
tomcat_1    | 	at com.csselect.API.httpAPI.Servlet.doPost(Servlet.java:97)
tomcat_1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
tomcat_1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
tomcat_1    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
tomcat_1    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
tomcat_1    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
tomcat_1    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
tomcat_1    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
tomcat_1    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
tomcat_1    | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
tomcat_1    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
tomcat_1    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
tomcat_1    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
tomcat_1    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
tomcat_1    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
tomcat_1    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
tomcat_1    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
tomcat_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
tomcat_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tomcat_1    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
tomcat_1    | 	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by SeineEloquenz** [comment]
> i also get the following in the tomcat log:
> 
> ```
> java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'database' at line 1

What is the name of the game database used?

**Comment by bendixsonnenberg** [comment]
the database is called ``database``

**Comment by SeineEloquenz** [comment]
weird, because in the sqlstatement database isn't written anywhere

**Comment by bendixsonnenberg** [comment]
``` SQL 
           DATABASE_ADAPTER.executeMysqlUpdate("INSERT INTO players (email,invited) VALUES " + values
                    + " ON DUPLICATE KEY UPDATE email=email;", getDatabaseName(), params);
```
this is the method that calls it, are you sure that getDatabaseName is not used in the sql statment?

**Comment by SeineEloquenz** [comment]
Yes, getDatabaseName() will be used to create a DataSource object from which the connection will be retrieved and the query executed on, i'll investigate further

**Comment by SeineEloquenz** [comment]
It seems like the gamecreation js doesn't even submit the featureset name

**Comment by bendixsonnenberg** [comment]
yes i have seen that and am working on it

> It seems like the gamecreation js doesn't even submit the featureset name

**Comment by SeineEloquenz** [comment]
> i also get the following in the tomcat log:
> 
> ```
> java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'database' at line 1
> tomcat_1    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
> tomcat_1    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
> tomcat_1    | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
> tomcat_1    | 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
> tomcat_1    | 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
> tomcat_1    | 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
> tomcat_1    | 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207)
> tomcat_1    | 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:402)
> tomcat_1    | 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:125)
> tomcat_1    | 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:110)
> tomcat_1    | 	at com.csselect.database.mysql.MysqlDatabaseAdapter.executeMysqlUpdate(MysqlDatabaseAdapter.java:370)
> tomcat_1    | 	at com.csselect.database.mysql.MysqlGameAdapter.addInvitedPlayers(MysqlGameAdapter.java:246)
> tomcat_1    | 	at com.csselect.game.Game.invitePlayers(Game.java:219)
> tomcat_1    | 	at com.csselect.game.gamecreation.GameCreator.doCreate(GameCreator.java:109)
> tomcat_1    | 	at com.csselect.user.Organiser.createGame(Organiser.java:73)
> tomcat_1    | 	at com.csselect.API.APIFacadeOrganiser.createGame(APIFacadeOrganiser.java:138)
> tomcat_1    | 	at com.csselect.API.httpAPI.GameManagement.createGame(GameManagement.java:150)
> tomcat_1    | 	at com.csselect.API.httpAPI.GameManagement.post(GameManagement.java:58)
> tomcat_1    | 	at com.csselect.API.httpAPI.Servlet.doPost(Servlet.java:97)
> tomcat_1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
> tomcat_1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> tomcat_1    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> tomcat_1    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
> tomcat_1    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
> tomcat_1    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
> tomcat_1    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
> tomcat_1    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> tomcat_1    | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
> tomcat_1    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
> tomcat_1    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
> tomcat_1    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
> tomcat_1    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
> tomcat_1    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
> tomcat_1    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
> tomcat_1    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> tomcat_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
> tomcat_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> tomcat_1    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> tomcat_1    | 	at java.base/java.lang.Thread.run(Thread.java:844)
> ```

As I don't really understand how this came to be please give me instructions on how to reproduce the bug if it should ever occur again @bendixsonnenberg

**Comment by SeineEloquenz** [comment]
There are no nullpointers occuring anymore on my machine and Features correctly reach the frontend, can you confirm @bendixsonnenberg so we can close this issue?

**Comment by bendixsonnenberg** [comment]
> @SeineEloquenz i cant reproduce the javascript errors, and i am still getting a null pointer exception when calling startRound
> 
> ```
> java.lang.NullPointerException
> 	com.csselect.game.Round.setGame(Round.java:49)
> 	com.csselect.game.Game.startRound(Game.java:283)
> 	com.csselect.user.Player.lambda$startRound$2(Player.java:79)
> 	java.base/java.lang.Iterable.forEach(Iterable.java:75)
> 	com.csselect.user.Player.startRound(Player.java:77)
> 	com.csselect.API.APIFacadePlayer.startRound(APIFacadePlayer.java:129)
> 	com.csselect.API.httpAPI.Games.startRound(Games.java:108)
> 	com.csselect.API.httpAPI.Games.post(Games.java:64)
> 	com.csselect.API.httpAPI.Servlet.doPost(Servlet.java:97)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> 	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53
> ```

has this been addressed? 
Because i'm still getting the same

**Comment by SeineEloquenz** [comment]
I don't get these, when do these nullpointers occur exactly?

**Comment by bendixsonnenberg** [comment]
when starting a game as a player
![image](https://user-images.githubusercontent.com/25992157/52093639-3680c980-25bc-11e9-8be4-33e4462a9942.png)

**Comment by SeineEloquenz** [comment]
Can you please debug method startRound in Game.java and debug whether it runs into the null returning if statement or the last return null statement

**Comment by bendixsonnenberg** [comment]
```
java.io.FileNotFoundException: /var/www/cs-select/dataSetName/summary.json (No such file or directory)
tomcat_1    | 	at java.base/java.io.FileInputStream.open0(Native Method)
tomcat_1    | 	at java.base/java.io.FileInputStream.open(FileInputStream.java:220)
tomcat_1    | 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
tomcat_1    | 	at java.base/java.io.FileReader.<init>(FileReader.java:72)
tomcat_1    | 	at com.csselect.utils.FeatureSetUtils.loadFeatureSet(FeatureSetUtils.java:38)
tomcat_1    | 	at com.csselect.database.mysql.MysqlGameAdapter.getFeatures(MysqlGameAdapter.java:80)
tomcat_1    | 	at com.csselect.game.Game.getFeatureSet(Game.java:134)
tomcat_1    | 	at com.csselect.game.Round.setGame(Round.java:49)
tomcat_1    | 	at com.csselect.game.Game.startRound(Game.java:283)
tomcat_1    | 	at com.csselect.user.Player.lambda$startRound$2(Player.java:79)
tomcat_1    | 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
tomcat_1    | 	at com.csselect.user.Player.startRound(Player.java:77)
tomcat_1    | 	at com.csselect.API.APIFacadePlayer.startRound(APIFacadePlayer.java:129)
tomcat_1    | 	at com.csselect.API.httpAPI.Games.startRound(Games.java:108)
tomcat_1    | 	at com.csselect.API.httpAPI.Games.post(Games.java:64)
tomcat_1    | 	at com.csselect.API.httpAPI.Servlet.doPost(Servlet.java:97)
tomcat_1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
tomcat_1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
tomcat_1    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
tomcat_1    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
tomcat_1    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
tomcat_1    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
tomcat_1    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
tomcat_1    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
tomcat_1    | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
tomcat_1    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
tomcat_1    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
tomcat_1    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
tomcat_1    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
tomcat_1    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
tomcat_1    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
tomcat_1    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
tomcat_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
tomcat_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tomcat_1    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
```
i went into the container and checked the homedir and found the populationGender dir:
```
root@1232680cfcc4:/var/www/cs-select/populationGender# ls
acne.png	   dbp_class.png	    drinkweek.png	   fedup_class.png	      height.png	      moody_class.png	  sleep.png		  stroke_class.png
acne_class.png	   depressed.png	    drinkweek_class.png    feethour.png		      height_class.png	      nerves.png	  sleep_class.png	  summary.json
age.png		   depressed_class.png	    educ.png		   feethour_class.png	      highchol.png	      nerves_class.png	  smokeagequit.png	  sunburn.png
age_class.png	   diabetes.png		    educ_class.png	   fh.age.png		      highchol_class.png      nervous.png	  smokeagequit_class.png  sunburn_class.png
asthma.png	   diabetes_class.png	    embarrassed.png	   fh.age_class.png	      hurt.png		      nervous_class.png   smokeever.png		  tense.png
asthma_class.png   dog.png		    embarrassed_class.png  fh.cancer.png	      hurt_class.png	      nofriend.png	  smokeever_class.png	  tense_class.png
cancer.png	   dog_class.png	    ethnicity.png	   fh.cancer_class.png	      hypertension.png	      nofriend_class.png  smokenow.png		  weight.png
cancer_class.png   drinkfreqweek.png	    ethnicity_class.png    fh.heartdisease.png	      hypertension_class.png  numhouse.png	  smokenow_class.png	  weight_class.png
cat.png		   drinkfreqweek_class.png  exermod.png		   fh.heartdisease_class.png  marital.png	      numhouse_class.png  smokeyears.png	  worrier.png
cat_class.png	   drinkmaxday.png	    exermod_class.png	   hand.png		      marital_class.png       pulse.png		  smokeyears_class.png	  worrier_class.png
cholest.png	   drinkmaxday_class.png    exervig.png		   hand_class.png	      miserable.png	      pulse_class.png	  snore.png		  worry.png
cholest_class.png  drinkmonth.png	    exervig_class.png	   heartattack.png	      miserable_class.png     sbp.png		  snore_class.png	  worry_class.png
dbp.png		   drinkmonth_class.png     fedup.png		   heartattack_class.png      moody.png		      sbp_class.png	  stroke.png
```
but it seems that the loadFeatureSet method does not use the correct featuresSet name

**Comment by SeineEloquenz** [comment]
Can you send me a dump of the games table of the cs_select database?

**Comment by bendixsonnenberg** [comment]
> Can you please debug method startRound in Game.java and debug whether it runs into the null returning if statement (and if why) or the last return null statement

runs into neither of the two cases

**Comment by bendixsonnenberg** [comment]
here you go
[Dump20190201.zip](https://github.com/bendixsonnenberg/CS-Select/files/2819553/Dump20190201.zip)

**Comment by SeineEloquenz** [comment]
Apparently the isTerminated column in games wasn't initialised to 0 but null, as is in your dump. I pushed a fix. Can you create a new game and check if the bug still occurs on new games? And you have to correct the column values if you want to use these games

**Comment by bendixsonnenberg** [comment]
``` java
    @Override
    public FeatureSet getFeatures() {
        try {
            return FeatureSetUtils.loadFeatureSet("dataSetName");
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }
```
this is the getFeatureMethod in MysqlGameAdapter
shouldn't the parameter in FeatureSetUtils.loadFeatureSet("dataSetName"); somehow get the dataSetName and not look for the dataset literally named 'dataSetName'?

**Comment by SeineEloquenz** [comment]
Yeah it should, and ii already fixed this but forgot to commit, excuse me

**Comment by bendixsonnenberg** [comment]
now the statGame does return a collection of features.
Thank you all very much for your help and sorry for keeping you up so late
