### ISSUE TITLE
No error when leaving termination condition empty

### ISSUE THREAD

**Issue by Santaaa348** [bendixsonnenberg/CS-Select#198]
Choose a termination (e.g. rounds), but don't enter a number of rounds. No database entry is made, however no alert (error message) is shown either.

**Comment by Weitspringer** [comment]
Does this occur only with rounds termination?

**Comment by Santaaa348** [comment]
No, also with time termination. You can leave the date empty and same things happen.

**Comment by bendixsonnenberg** [comment]
Will look into this as soon as #191 is merged
