### ISSUE TITLE
Terminated games not disappearing from the overview

### ISSUE THREAD

**Issue by SeineEloquenz** [bendixsonnenberg/CS-Select#24]
After clicking on terminate on a game in the active games list on the organiser dashboard the game is not removed from the list until the page is reloaded

**Comment by bendixsonnenberg** [comment]
currently that is the expected behaviour

**Comment by SeineEloquenz** [comment]
Should this really be expected behavior? I think some kind of indication that the game was removed would be useful, e.g. at least graying out the button

**Comment by bendixsonnenberg** [comment]
ill set this a an enhancement and work on it if there is time
