### ISSUE TITLE
Feature.java getDesc returns null

### ISSUE THREAD

**Issue by bendixsonnenberg** [bendixsonnenberg/CS-Select#25]
as said in the title

**Comment by Biekachuu** [comment]
Found no issue in Feature Class, is every setter always called when creating a feature?

**Comment by SeineEloquenz** [comment]
Error seems to lie in the loading of features from the disk, gonna investigate ASAP

**Comment by SeineEloquenz** [comment]
Fixed, but \n values in the description don't get turned into breaks on the cards, someone with frontend knowledge please investigate this

**Comment by bendixsonnenberg** [comment]
7b28bb904dc5e9d0f46fa3dadd8cd7e61fd8ad5b
addressed in here
