### ISSUE TITLE
Player.selectFeatures does nothing

### ISSUE THREAD

**Issue by bendixsonnenberg** [bendixsonnenberg/CS-Select#26]
when the api calls Player.selectFeatures, no new entries in the database are made, the streak is not increased and no points are added to the player.
Also there is no exception thrown, neither in the tomcat log nor in the response from tomcat.

**Comment by bendixsonnenberg** [comment]
Steps to reproduce:
- create game as organiser
- play game as player and see that neither the streak nor the score has been increased

**Comment by Weitspringer** [comment]
`     * Calling this method means to actually play the active round and retrieving a score.
     * @param selectedFeatures Features the player has selected for this round
     * @param uselessFeatures Features the player marked as unimportant
     * @return Integer representing score
     */
    public void selectFeatures(int[] selectedFeatures, int[] uselessFeatures) {
        activeRound.selectFeatures(selectedFeatures, uselessFeatures);
    public int selectFeatures(int[] selectedFeatures, int[] uselessFeatures) {
        return activeRound.selectFeatures(selectedFeatures, uselessFeatures);
    }

    /**`

**Comment by Weitspringer** [comment]
Player.selectFeatures now returns score

**Comment by Weitspringer** [comment]
#27

**Comment by Weitspringer** [comment]
Working on request #27

**Comment by bendixsonnenberg** [comment]
![image](https://user-images.githubusercontent.com/25992157/52121417-d885cd80-261f-11e9-9599-4234525fba54.png)
playround now returns -1

**Comment by Biekachuu** [comment]
Found an issue and pushed a fix, please try again.
Related question: if there are no useless features selected, does the method call include an empty array or null as a parameter?

**Comment by bendixsonnenberg** [comment]
empty array

**Comment by bendixsonnenberg** [comment]
![image](https://user-images.githubusercontent.com/25992157/52130593-e137cd00-263a-11e9-8951-6f51c8f5b750.png)
points are now returned, but it takes quite long
the playerStats table is updated, but in the game database no new round entries are made 
![image](https://user-images.githubusercontent.com/25992157/52130685-26f49580-263b-11e9-9670-32444754e7ee.png)

**Comment by SeineEloquenz** [comment]
Entries should now be created, please verify

**Comment by bendixsonnenberg** [comment]
rounds are now entered into the database
