### ISSUE TITLE
getting information about whether a featureSet exists on  the mlServer

### ISSUE THREAD

**Issue by bendixsonnenberg** [bendixsonnenberg/CS-Select#29]
It would be great if we could tell the user if the dataset they described did not exist, so would it be possible to somehow send that information from the backend to the user?

maybe through an exception, although that would implement logic through exceptions, which would not be best practive

**Comment by SeineEloquenz** [comment]
I could change the necessary methods so that they return a null featureset if the given name doesn't exist, would this be a  solution?

**Comment by bendixsonnenberg** [comment]
No, because that signal would not reach the frontend

**Comment by bendixsonnenberg** [comment]
I would say that an exception is the best way to handle this. We can also add an exception for database already exists

**Comment by SeineEloquenz** [comment]
Do you need a checked exception or a runtime exception to get them in the frontend?

**Comment by bendixsonnenberg** [comment]
checked exception

**Comment by SeineEloquenz** [comment]
I added the new exceptions and necessary throws statements up until the organiser, handling in the API is still missing. 

Referring to branch newExceptions

**Comment by bendixsonnenberg** [comment]
I added the handeling in the api, but there are still unhandled exceptions that prevent compiling
