### ISSUE TITLE
Umlaute in features don't show correctly

### ISSUE THREAD

**Issue by SeineEloquenz** [bendixsonnenberg/CS-Select#37]
As in title
![image](https://user-images.githubusercontent.com/34923333/52133351-6faf4d00-2641-11e9-9fe5-bde2bd23f6e3.png)

**Comment by bendixsonnenberg** [comment]
cant reproduce 
![image](https://user-images.githubusercontent.com/25992157/52133929-b2bdf000-2642-11e9-948a-485b38f32c09.png)

**Comment by SeineEloquenz** [comment]
Google Chrome

**Comment by bendixsonnenberg** [comment]
cant reproduce in google chrome
![image](https://user-images.githubusercontent.com/25992157/52146753-017c8180-2665-11e9-8bae-27c071a97d70.png)

**Comment by SeineEloquenz** [comment]
Then maybe something is wrong on my end, gonna close this for now
