### ISSUE TITLE
Registering new organiser with wrong master password returns invalid response

### ISSUE THREAD

**Issue by Weitspringer** [bendixsonnenberg/CS-Select#45]
Message is "Email is already in use", change to "Obey! Wrong master password" or such

**Comment by bendixsonnenberg** [comment]
for this the api needs to get some kind of response from the OrganiserManagement that differentiates between email in use and wrong master password @Weitspringer

**Comment by SeineEloquenz** [comment]
We could make OrganiserManagement#register throw an IllegalArgumentException with an according message instead of returning null, would that be suitable?

**Comment by Weitspringer** [comment]
I am looking into it

**Comment by SeineEloquenz** [comment]
@Weitspringer are you still working on this?

**Comment by Weitspringer** [comment]
@SeineEloquenz This was idle

**Comment by Weitspringer** [comment]
@SeineEloquenz Somethings still wrong
