### ISSUE TITLE
Streak does not reset when skipping a round or logout

### ISSUE THREAD

**Issue by Santaaa348** [bendixsonnenberg/CS-Select#56]

**Comment by Santaaa348** [comment]
![streakfail](https://user-images.githubusercontent.com/37215789/52524190-b7198700-2c9a-11e9-8aae-63cb569a184f.PNG)
@bendixsonnenberg

**Comment by bendixsonnenberg** [comment]
which url was accessed?

**Comment by bendixsonnenberg** [comment]
or even better show me the request header and body

**Comment by Santaaa348** [comment]
![streeeak](https://user-images.githubusercontent.com/37215789/52526218-c5c16780-2cb5-11e9-84ed-ff152baa69e6.PNG)
Does this help?

**Comment by bendixsonnenberg** [comment]
Seems like the useless features were not sendOn Feb 9, 2019 22:00, Santaaa348 <notifications@github.com> wrote:
Does this help?

**Comment by bendixsonnenberg** [comment]
Found a mistake in the API, will push a fix soonOn Feb 9, 2019 22:29, "Bendix S." <bendix.sonnenberg@gmx.de> wrote:Seems like the useless features were not sendOn Feb 9, 2019 22:00, Santaaa348 <notifications@github.com> wrote:
Does this help?

**Comment by bendixsonnenberg** [comment]
that fixed it for me .
can you confirm?

**Comment by Santaaa348** [comment]
Yes, skipping a round now does reset the streak (maybe we should also warn the user that his streak would get reset?) But when logging out and back in, the streak remains the same.

**Comment by bendixsonnenberg** [comment]
it seems like on every login the same player object is returned, which means that the streak object is not discarded by the garbage collection.
I'm not entirely sure why this happens, as each time a new player object should be created
@Weitspringer @SeineEloquenz maybe you can shed some light on this?

here im printing the player.toString method of player to the console on each login:
```
tomcat_1    | logging in
tomcat_1    | com.csselect.user.Player@1 // player 1 is logging in, it is weird that the @ is followed by 1
tomcat_1    | player logged out // here the code player = null is executed, which is the only reference to that object that should exists. tried to open the dashboard, but no information was fetched from the api
tomcat_1    | logging in // trying to log in again
tomcat_1    | com.csselect.user.Player@1 // the same object ( first == second) which can't happen because no reference to that object has existed befor
tomcat_1    | player logged out
tomcat_1    | logging in
tomcat_1    | com.csselect.user.Player@2 // logging in with a different player
```

**Comment by Santaaa348** [comment]
The streak object belongs to a PlayerStats object which is not discarded as far as I know. So you'd have to set it manually?

**Comment by SeineEloquenz** [comment]
@bendixsonnenberg 
If I recall correctly the @1 is specifying the hashcode of the player, as we overwrite the `User::hashcode()` method, the hashcode of these objects is always their id

**Comment by SeineEloquenz** [comment]
@Santaaa348 Every player is using the same PlayerStats object, that's correct. I thought this is expected behaviour?

**Comment by Santaaa348** [comment]
Yes, this was supposed to be an explanation to @bendixsonnenberg.

**Comment by bendixsonnenberg** [comment]
> @bendixsonnenberg
> If I recall correctly the @1 is specifying the hashcode of the player, as we overwrite the `User::hashcode()` method, the hashcode of these objects is always their id

didn't know that. in that case disregard my comment

**Comment by bendixsonnenberg** [comment]
now i see where the playstats are kept in memory.
this means that somehow the playstats object needs to be notified whenever the player logs out.
Or don't reset streaks when the player logs out

**Comment by Santaaa348** [comment]
Second solution would defeat the purpose of the streak. So yes, we somehow have to implement the first one.

**Comment by bendixsonnenberg** [comment]
if playerstats had a logout method, that got called every time the player logs out, that method could be called from the player and solve this

**Comment by Santaaa348** [comment]
#144
