### ISSUE TITLE
German translation incomplete

### ISSUE THREAD

**Issue by NicoWeidmann** [bendixsonnenberg/CS-Select#60]
The following elements don't have a german translation

- [x] update buttons in organizer settings view
- [ ] "new password" help text in password text box of organizer settings view
- [x] error messages shown via alert when clicking on "create" button during game creation (in case of missing input)
- [x] content hints in text boxes (e.g. "password") on login screen

**Comment by Jakob-Bach** [comment]
- [ ] "Help" label on organizer overview

**Comment by SeineEloquenz** [comment]
The "new password" is already localised, but is still not shown in german in the browser, I don't understand why, could you investigate @bendixsonnenberg?
