### ISSUE TITLE
Test data is shown when loading organizer dashboard

### ISSUE THREAD

**Issue by NicoWeidmann** [bendixsonnenberg/CS-Select#62]
The dashboard shows what looks like test data for both active and terminated games when loading the page. This data vanishes immediately.

**Comment by NicoWeidmann** [comment]
This also applies to the player dashboard.

**Comment by bendixsonnenberg** [comment]
> This also applies to the player dashboard.

What testing data is show?
I can't reproduce it on the player dashboard

**Comment by NicoWeidmann** [comment]
> What testing data is show?
The username initially shows as "Bendix" with score "1234".
