### ISSUE TITLE
Game Creation: user input should be validated

### ISSUE THREAD

**Issue by NicoWeidmann** [bendixsonnenberg/CS-Select#65]
The system should validate entered by an organizer when creating a new game:
It is possible to enter text instead of a number when setting the maximum number of rounds and the game still shows up as active.
It is possible to enter "30:00" as termination time. The system shows "Game sucessfully created", but the game doesn't show up.

**Comment by NicoWeidmann** [comment]
It is also possible to create games in MatrixSelect mode where the number of features to be selected is greater than the number of shown features.

**Comment by bendixsonnenberg** [comment]
has been addressed in #122
