### ISSUE TITLE
Consistency: System doesn't check if email is in use when changing email

### ISSUE THREAD

**Issue by NicoWeidmann** [bendixsonnenberg/CS-Select#74]
To recreate:

1. create 2 user accounts with different email addresses
2. log into one of the accounts and change email so that both accounts use the same address
3. system doesn't show any error message

**Comment by NicoWeidmann** [comment]
With my current setup, both users have the same password. Signing in using the duplicate email and password, I'm logged in as a third, different user (organizer), but the player dashboard is shown.

**Comment by Weitspringer** [comment]
@SeineEloquenz I need an Exception from the database to catch (IllegalArgumentException for example) if Email still exists

**Comment by Weitspringer** [comment]
987005bf5ad05ffc4e38f27f047148796c051a70
