### ISSUE TITLE
[bug] Fix feature order for database

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#79]
`MysqlGameAdapter::checkDuplicateFeatureProvision()` compares against a stringified list of feature ids, but the order in the feature list is not guaranteed (e.g., `StandardRound::provideFeatures()`), so the same feature set might be provided just in a different order. Feature ids might be ordered before writing them to the database or just after determining them (first one probably preferable, as 2nd solution requires maintaining the order over a whole set of steps in the application's internal workflow) or maybe in `FeatureSet`. Decide yourself what the best way is (also considering evolution, e.g. new Round or database-related classes).

**Comment by SeineEloquenz** [comment]
Addressed in dea7e7940713c410f1c407a89e0616e7990db09e
