### ISSUE TITLE
[bug] Server fails violently if config not present

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#81]
If the file `config.properties` does not exist as expected (e.g., different name), you can still start the application. However, when trying to register, you get the message that the e-mail is already taken (even if it's not - in my case, the *cs_select* database wasn't even created) and tomcat crashes completely (closes it's window, so you need to be fast to even copy the error messages). An understandable error message in the browser (and no tomcat crash) would be nice.

**Comment by SeineEloquenz** [comment]
Changed the configuration so it throws an exception when an error occurs while reading the config file. Can now be caught and send an error message to the user on the frontend @bendixsonnenberg.

Referring to branch configurationException

**Comment by SeineEloquenz** [comment]
Fixed with #130
