### ISSUE TITLE
[gui][low prio] Game Creation: Improve message if ML server is down

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#83]
If the ML server is down and you try to create a game, the website tells you that the feature set is not available and a `java.net.SocketTimeoutException` is thrown. A message stating that the ML server is not available would be better.
As a plus: You could even notify the organiser on log-in that the ML server is not available (using `GET /version` as check), so the organiser is prepared that some things might not work as expected.

**Comment by SeineEloquenz** [comment]
MLServer Interface now has a isOnline() method to check whether the MLServer is reachable or not

(As of 9ad1884 on gamecreationFrontendRewrite)
