### ISSUE TITLE
[feature-request][low prio] Organiser Settings: Make password change less error-prone

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#87]
2nd input field to confirm password or show password so that the user can make sure that there are no typos in it.

**Comment by Weitspringer** [comment]
resolved from f387077a33b38f2b183a5706e8fcdb9e862da2df

**Comment by Santaaa348** [comment]
Has this commit been reverted? 🤔 @Weitspringer It's not on master.

**Comment by SeineEloquenz** [comment]
Yes it has been, as it was on the wrong branch and did not work properly

**Comment by Weitspringer** [comment]
On your machine at leas, @SeineEloquenz

**Comment by SeineEloquenz** [comment]
Passwords not equal hint is shown even if nothing has been entered
![image](https://user-images.githubusercontent.com/34923333/53034830-5d704400-3474-11e9-8ede-93d79a925540.png)
Passwords not equal hint is shown even if the same passwords have been entered
![image](https://user-images.githubusercontent.com/34923333/53034851-71b44100-3474-11e9-9ea7-b1eb11915fbd.png)
After updating the password the hint is not shown until the first password field is edited even if the second one was before
![image](https://user-images.githubusercontent.com/34923333/53034925-97414a80-3474-11e9-8148-ac13dabfd670.png)
