### ISSUE TITLE
[gui] Player Overview: Improve layout

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#88]
![screenshot](https://user-images.githubusercontent.com/6431179/52404807-30ae4b00-2aca-11e9-94b5-5b12eef64a6f.PNG)

- [x] Margin around daily challenge/alignment of text
- [x] Maybe explicitly write above daily challenge that it is a daily challenge (else users might be wondering what this means)
- [x] Mysterious zeros (I suppose that are points, but it's not clear for an inexperienced user)
- [ ] (might be addressed separately) The rules of a game are not clear, e.g., in MatrixSelect, how many features have to be selected (can be found out by trial and error, but showing it would be nicer). Plus, the termination criterion might also be interesting to see for players.

**Comment by bendixsonnenberg** [comment]
#129 opend new issue for user information matrix select
