### ISSUE TITLE
[bug] Useless features not written to database

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#89]
Tested with binary selection.

**Comment by bendixsonnenberg** [comment]
does this still happen?
are there special steps needed to provoke this behaviour?
currently I can't reproduce this

**Comment by bendixsonnenberg** [comment]
in case this was in respect to skip round, this is fixed as of 
93568195a1380f7eb47baa542f975d8860ea776c
