### ISSUE TITLE
Overly long tooltip text when playing

### ISSUE THREAD

**Issue by NicoWeidmann** [bendixsonnenberg/CS-Select#92]
a very long tooltip text is shown with instructions on how to play. This text shows when hovering over any button.

Ideally, only the text relevant to a particular button should be shown when hovering it. Maybe add a "help" button in the top-right corner that opens an overlay with the help text.

The text also shows when hovering anywhere if the graph overlay is shown.

**Comment by bendixsonnenberg** [comment]
#142
