### ISSUE TITLE
[bug] I got my name changed - Auto-logout?

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#95]
I played some rounds and the game ended. I did nothing for > 30 min, came back and clicked on the "end game" button. I was re-directed to the following screen:

![screenshot](https://user-images.githubusercontent.com/6431179/52408016-1e380f80-2ad2-11e9-8d5e-ad993c60b96c.PNG)

Was the session terminated and this is some kind of default player overview? Anyway, it's quite confusing. I could log out and then log-in with my credentials again, my points were retrieved correctly.

**Comment by bendixsonnenberg** [comment]
30 minutes is the time that a session in tomcat runs out, so this is another instance of #31
