### ISSUE TITLE
[gui][bug] No tooltips for Firefox

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#98]
I've read that there should be tooltips. I haven't seen one with Firefox yet,

**Comment by Jakob-Bach** [comment]
Update: In MatrixSelect mode I get a tooltip for the buttons under the feature description, although it's the same tooltip for all three buttons (as mentioned in some other issue).

**Comment by bendixsonnenberg** [comment]
#142
