### ISSUE TITLE
[bug] No features in matrix select

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#99]
![screenshot](https://user-images.githubusercontent.com/6431179/52409595-39a51980-2ad6-11e9-98bb-f961e58a1f26.PNG)

First round of game, 100 rounds matrix select, 4-5 out of 10 features. Firefox. The HTML source looks like this:

```html
<div class="col-10">
  <!---->
</div>
```

**Comment by NicoWeidmann** [comment]
Reproduced in Google Chrome.

**Comment by bendixsonnenberg** [comment]
the issue could be that 10 is not a square number, so the frontend does not now how to display the matrix

the gamecreation should check that the numberoffeatures is a square number

**Comment by NicoWeidmann** [comment]
Maybe the system should also allow non-square feature counts. You could place the features with the following strategy:

- Determine how many features fit into one row (according to screen space)
- add rows as needed, last row might contain less features than previous rows
